# Generated by Django 6.0.4 on 2026-04-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('point_won', 'Point Won'), ('point_lost', 'Point Lost'), ('substitution', 'Substitution'), ('timeout', 'Timeout'), ('rotation', 'Rotation'), ('undo', 'Undo')], max_length=20)),
                ('set_number', models.PositiveIntegerField()),
                ('rotation', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_undone', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('kill', 'Kill'), ('block', 'Block'), ('ace', 'Ace'), ('assist', 'Assist'), ('dig', 'Dig'), ('serve_error', 'Serve Error'), ('attack_error', 'Attack Error'), ('opponent_error', 'Opponent Error')], max_length=20)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='matches.action')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_set', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('our_serve', models.BooleanField(default=True)),
                ('current_rotation', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='schedule.match')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='live_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='matches.livematch'),
        ),
        migrations.CreateModel(
            name='SetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('our_score', models.PositiveIntegerField(default=0)),
                ('opponent_score', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('live_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_scores', to='matches.livematch')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('live_match', 'set_number')},
            },
        ),
    ]
