# Generated by Django 6.0.4 on 2026-04-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_live_match_setup_fields'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='libero_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libero_assignments', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('point_won', 'Point Won'), ('point_lost', 'Point Lost'), ('sideout', 'Sideout'), ('substitution', 'Substitution'), ('timeout', 'Timeout'), ('rotation', 'Rotation'), ('undo', 'Undo'), ('lineup', 'Lineup'), ('match_start', 'Match Start'), ('technical_timeout', 'Technical Timeout')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlayerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_played', models.PositiveIntegerField(default=0)),
                ('currently_on_court', models.BooleanField(default=False)),
                ('stint_started_at', models.DateTimeField(blank=True, null=True)),
                ('live_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='matches.livematch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='teams.player')),
            ],
            options={
                'unique_together': {('live_match', 'player')},
            },
        ),
    ]
