# Generated by Django 6.0.4 on 2026-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_ruleset',
            field=models.CharField(choices=[('fivb_best_of_5', 'FIVB Indoor - Best of 5'), ('best_of_3', 'Short Match - Best of 3'), ('training_scrimmage', 'Training Scrimmage')], default='fivb_best_of_5', max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='default_substitution_limit',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='team',
            name='preferred_first_server',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='preferred_lineup',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
