# Generated by Django 6.0.4 on 2026-04-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Passing', 'Passing'), ('Serving', 'Serving'), ('Hitting', 'Hitting'), ('Blocking', 'Blocking'), ('Defense', 'Defense'), ('Setting', 'Setting'), ('Game-like', 'Game-like')], max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('players_needed', models.CharField(max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('planned_duration', models.CharField(blank=True, max_length=20)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drill')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_drills', to='schedule.practice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DrillObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_performed', models.BooleanField(default=False)),
                ('actual_duration', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('practice_drill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='drills.practicedrill')),
            ],
        ),
    ]
