# Generated by Django 5.2.13 on 2026-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_club_id_alter_user_id_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_blind_mode',
            field=models.CharField(choices=[('off', 'Off'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia')], default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
    ]
