# Generated by Django 6.0.4 on 2026-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_match_title_ruleset'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='substitution_limit',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
